---
# handlers file for db-tier
- name: Postgres init
  command: postgresql-setup initdb
  args:
    creates: /var/lib/pgsql/data/postgres

- name: Postgres chkconfig
  command: chkconfig postgresql on
  args:
    creates: /var/lib/pgsql/data/postgres

- name: Start/enable postgres
  service:
    name: postgresql
    state: started
    enabled: yes
