---
# tasks file for app-tier
#
- name: Installing tomcat
  package:
    name: tomcat
    state: latest

- name: create directory for tomcat ansible
  file:
    path: "{{ tomcat_dir }}"
    state: directory

- name: copy index template to tomcat
  copy:
    src: index.html.j2
    dest: "{{ tomcat_dir }}"
    mode: 0644
  notify: restart/enable tomcat

- name: Installing apache
  yum:
    name: httpd
    state: latest
  notify: restart/enable apache
